window.WONDER_LOBBY = {
  platform: {
    name: "WeightPlay",
    company: "WeightStudio",
    tagline: {
      en: "Play animal games made for every age.",
      "zh-Hant": "適合各年齡的動物遊戲。",
    },
    subtitle: {
      en: "A growing animal browser game world for kids, families, and casual players.",
      "zh-Hant": "為孩子、家庭與休閒玩家打造的動物瀏覽器遊戲世界。",
    },
    defaultLocale: "en",
  },
  featuredGameId: "animal-guard-yard",
  heroGameIds: ["animal-guard-yard", "snack-blocks", "wonder-crash"],
  games: [
    {
      id: "wonder-crash",
      title: { en: "Lion Wonder Crash", "zh-Hant": "奇幻獅子守城" },
      status: "playable",
      statusText: { en: "Playable", "zh-Hant": "可遊玩" },
      type: { en: "Animal Defense", "zh-Hant": "動物防衛" },
      categories: ["Featured", "Animal Games", "Arcade"],
      skills: ["Reaction", "Focus", "Hand-Eye Coordination"],
      ages: ["5"],
      ageLabel: "5+",
      href: "games/wonder-crash/",
      description: {
        en: "Help the lion mascot guard a fantasy wall with playful school-supply weapons.",
        "zh-Hant": "幫助獅子主角用有趣的文具武器守住奇幻城牆。",
      },
      meta: {
        en: ["Lion Hero", "30 Levels", "Diamond Upgrades"],
        "zh-Hant": ["獅子英雄", "30 關", "鑽石強化"],
      },
      art: {
        kind: "image",
        background: "assets/wonder-crash-cover.webp",
        hero: "assets/hero.png",
        hideHero: true,
      },
    },
    {
      id: "color-lunchbox",
      title: { en: "Animal Color Lunchbox", "zh-Hant": "動物顏色便當盒" },
      status: "playable",
      statusText: { en: "Playable", "zh-Hant": "可遊玩" },
      type: { en: "Color Match", "zh-Hant": "顏色配對" },
      categories: ["Animal Games", "Education", "Family"],
      skills: ["Color Recognition", "Focus", "Hand-Eye Coordination"],
      ages: ["3", "family"],
      ageLabel: "3+",
      href: "games/color-lunchbox/",
      description: {
        en: "Help little animals sort colorful foods through themed lunchbox challenges.",
        "zh-Hant": "幫小動物把不同顏色的食物放進正確便當盒。",
      },
      meta: {
        en: ["Animal Theme", "12 Levels", "Drag Match"],
        "zh-Hant": ["動物主題", "12 關", "拖曳配對"],
      },
      art: {
        kind: "image",
        background: "assets/lunchbox-cover.png",
        hero: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='1' height='1'></svg>",
      },
    },
    {
      id: "bubble-bakery",
      title: { en: "Animal Bubble Bakery", "zh-Hant": "動物泡泡烘焙坊" },
      status: "playable",
      statusText: { en: "Playable", "zh-Hant": "可遊玩" },
      href: "games/bubble-bakery/",
      type: { en: "Bubble Puzzle", "zh-Hant": "泡泡益智" },
      categories: ["Animal Games", "Puzzle", "Family"],
      skills: ["Logic", "Problem Solving", "Focus"],
      ages: ["5", "family"],
      ageLabel: { en: "5+", "zh-Hant": "5+" },
      description: {
        en: "Help animal bakers tap matching bubbles, fill cozy orders, and clear puzzle stages.",
        "zh-Hant": "幫動物烘焙師點擊相同泡泡，完成溫馨訂單。",
      },
      meta: {
        en: ["Animal Bakery", "6 Stages", "Tap Groups"],
        "zh-Hant": ["動物烘焙", "6 關", "點擊群組"],
      },
      art: {
        kind: "image",
        background: "assets/bubble-bakery-cover.webp",
        hero: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='1' height='1'></svg>",
      },
    },
    {
      id: "animal-zoo-idle",
      title: { en: "Animal Zoo Idle", "zh-Hant": "動物小小樂園" },
      status: "playable",
      statusText: { en: "Playable", "zh-Hant": "可遊玩" },
      href: "games/animal-zoo-idle/",
      type: { en: "Idle Zoo", "zh-Hant": "放置樂園" },
      categories: ["Featured", "Animal Games", "Family"],
      skills: ["Logic", "Focus", "Animal Knowledge"],
      ages: ["5", "family"],
      ageLabel: { en: "5+", "zh-Hant": "5+" },
      description: {
        en: "Run a safari meadow where visitors buy tickets while you feed animals and upgrade the park.",
        "zh-Hant": "經營草原動物園，讓遊客買票參觀，餵食動物並升級樂園。",
      },
      meta: {
        en: ["Idle Zoo", "Ticket Income", "Animal Feeding"],
        "zh-Hant": ["放置樂園", "票箱收益", "餵食動物"],
      },
      art: {
        kind: "image",
        background: "assets/animal-zoo-idle-cover.webp",
        hero: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='1' height='1'></svg>",
      },
    },
    {
      id: "star-memory",
      title: { en: "Animal Star Memory", "zh-Hant": "動物星星翻牌" },
      status: "playable",
      statusText: { en: "Playable", "zh-Hant": "可遊玩" },
      href: "games/star-memory/",
      type: { en: "Memory Puzzle", "zh-Hant": "記憶益智" },
      categories: ["Animal Games", "Puzzle", "Family"],
      skills: ["Memory", "Focus", "Problem Solving"],
      ages: ["5", "family"],
      ageLabel: "5+",
      description: {
        en: "Clear memory stages by matching stars, animals, and friendly picture cards.",
        "zh-Hant": "翻開星星與動物卡片，完成一關關記憶挑戰。",
      },
      meta: {
        en: ["Animal Cards", "10 Levels", "Memory"],
        "zh-Hant": ["動物卡片", "10 關", "記憶力"],
      },
      art: {
        kind: "image",
        background: "assets/memory-cover.png",
        hero: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='1' height='1'></svg>",
      },
    },
    {
      id: "campus-dash",
      title: { en: "Safari Dash", "zh-Hant": "草原閃電跑" },
      status: "playable",
      statusText: { en: "Playable", "zh-Hant": "可遊玩" },
      href: "games/campus-dash/",
      type: { en: "Reaction Runner", "zh-Hant": "反應跑酷" },
      categories: ["Animal Games", "Arcade"],
      skills: ["Reaction", "Focus", "Hand-Eye Coordination"],
      ages: ["12"],
      ageLabel: "12+",
      description: {
        en: "Swipe left and right, dodge safari trail obstacles, and chase a high score.",
        "zh-Hant": "左右閃避草原障礙，挑戰更高分數。",
      },
      meta: {
        en: ["Safari", "Score Attack", "60 Sec"],
        "zh-Hant": ["草原", "分數挑戰", "60 秒"],
      },
      art: {
        kind: "image",
        background: "assets/campus-dash-cover.webp",
        hero: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='1' height='1'></svg>",
      },
    },
    {
      id: "snack-blocks",
      title: { en: "Animal Snack Blocks", "zh-Hant": "動物零食方塊" },
      status: "playable",
      statusText: { en: "Playable", "zh-Hant": "可遊玩" },
      href: "games/snack-blocks/",
      type: { en: "Match Puzzle", "zh-Hant": "消除益智" },
      categories: ["Featured", "Animal Games", "Puzzle", "Family"],
      skills: ["Logic", "Problem Solving", "Focus"],
      ages: ["12", "family"],
      ageLabel: "12+",
      description: {
        en: "Match animal snacks, use every move, clear collection goals, and chase your best score.",
        "zh-Hant": "消除動物零食方塊，在有限步數內完成收集目標。",
      },
      meta: {
        en: ["Animal Snacks", "20 Stages", "Match Puzzle"],
        "zh-Hant": ["動物零食", "20 關", "消除益智"],
      },
      art: {
        kind: "image",
        background: "assets/snack-blocks-cover.webp",
        hero: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='1' height='1'></svg>",
      },
    },
    {
      id: "fruit-merge",
      title: { en: "Animal Fruit Merge", "zh-Hant": "動物水果合成" },
      status: "playable",
      statusText: { en: "Playable", "zh-Hant": "可遊玩" },
      href: "games/fruit-merge/",
      type: { en: "Score Puzzle", "zh-Hant": "分數益智" },
      categories: ["Animal Games", "Puzzle", "Family"],
      skills: ["Logic", "Problem Solving", "Hand-Eye Coordination"],
      ages: ["5", "family"],
      ageLabel: { en: "5+", "zh-Hant": "5+" },
      description: {
        en: "Feed the animal festival by dropping fruits, merging matching pairs, and chasing your best score.",
        "zh-Hant": "投下水果、合成更大的水果，替動物祭典累積高分。",
      },
      meta: {
        en: ["Animal Festival", "Fruit Merge", "Best Record"],
        "zh-Hant": ["動物祭典", "水果合成", "最佳紀錄"],
      },
      art: {
        kind: "image",
        background: "assets/fruit-merge-cover.webp",
        hero: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='1' height='1'></svg>",
      },
    },
    {
      id: "garden-tiles",
      title: { en: "Pet Garden Tiles", "zh-Hant": "寵物花園方塊" },
      status: "playable",
      statusText: { en: "Playable", "zh-Hant": "可遊玩" },
      href: "games/garden-tiles/",
      type: { en: "Relaxing Match", "zh-Hant": "放鬆配對" },
      categories: ["Animal Games", "Puzzle", "Family"],
      skills: ["Memory", "Focus", "Problem Solving"],
      ages: ["family"],
      ageLabel: { en: "Relax", "zh-Hant": "放鬆" },
      description: {
        en: "A large-print, no-timer pet garden matching game made for calm daily play.",
        "zh-Hant": "大字體、無壓力、沒有倒數的寵物花園配對遊戲。",
      },
      meta: {
        en: ["Pet Garden", "Large Tiles", "No Timer"],
        "zh-Hant": ["寵物花園", "大方塊", "無倒數"],
      },
      art: {
        kind: "image",
        background: "assets/garden-tiles-cover.webp",
        hero: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='1' height='1'></svg>",
      },
    },
    {
      id: "animal-rescue",
      title: { en: "Animal Rescue Trail", "zh-Hant": "動物回家路" },
      status: "playable",
      statusText: { en: "Playable", "zh-Hant": "可遊玩" },
      type: { en: "Animal Puzzle", "zh-Hant": "動物益智" },
      categories: ["Animal Games", "Puzzle", "Family"],
      skills: ["Logic", "Problem Solving", "Animal Knowledge"],
      ages: ["3", "5", "family"],
      ageLabel: { en: "Family", "zh-Hant": "親子" },
      href: "games/animal-rescue/",
      description: {
        en: "Tap gentle paths and guide cute animals back home.",
        "zh-Hant": "點選安全路線，帶可愛動物回到家。",
      },
      meta: {
        en: ["Animal Games", "12 Trails", "No Pressure"],
        "zh-Hant": ["動物遊戲", "12 條路線", "無壓力"],
      },
      art: {
        kind: "image",
        background: "assets/animal-rescue-cover.webp",
        hero: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='1' height='1'></svg>",
      },
    },
    {
      id: "animal-hidden-safari",
      title: { en: "Animal Hidden Safari", "zh-Hant": "動物探險找找看" },
      status: "playable",
      statusText: { en: "Playable", "zh-Hant": "可遊玩" },
      type: { en: "Hidden Object", "zh-Hant": "找找看" },
      categories: ["Animal Games", "Puzzle", "Family"],
      skills: ["Focus", "Animal Knowledge", "Problem Solving"],
      ages: ["3", "family"],
      ageLabel: { en: "3+", "zh-Hant": "3+" },
      href: "games/animal-hidden-safari/",
      description: {
        en: "Search playful safari scenes and find hidden animals, tracks, and habitat clues.",
        "zh-Hant": "觀察熱鬧的草原場景，找出藏起來的動物、腳印與棲地線索。",
      },
      meta: {
        en: ["Seek & Find", "6 Habitats", "No Pressure"],
        "zh-Hant": ["找找看", "6 個棲地", "無壓力"],
      },
      art: {
        kind: "image",
        background: "assets/animal-hidden-safari-cover.webp",
        hero: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='1' height='1'></svg>",
      },
    },
    {
      id: "animal-guard-yard",
      title: { en: "Animal Guard Yard", "zh-Hant": "動物守衛庭院" },
      status: "playable",
      statusText: { en: "Playable", "zh-Hant": "可遊玩" },
      type: { en: "Lane Defense", "zh-Hant": "路線防衛" },
      categories: ["Featured", "Animal Games", "Arcade", "Family"],
      skills: ["Logic", "Focus", "Problem Solving"],
      ages: ["5", "family"],
      ageLabel: { en: "5+", "zh-Hant": "5+" },
      href: "games/animal-guard-yard/",
      description: {
        en: "Place full-body animal guards, earn coins, upgrade your team, and fight through 8 zombie stages with boss battles.",
        "zh-Hant": "放置全身動物守衛，收集陽光、賺取金幣、升級隊伍，在 8 個關卡中擋住殭屍與 Boss 進攻。",
      },
      meta: {
        en: ["Hero Defense", "Animal Upgrades", "Boss Battles"],
        "zh-Hant": ["主打防衛", "動物升級", "Boss 戰"],
      },
      art: {
        kind: "image",
        background: "assets/animal-guard-yard-poster.webp",
        hero: "assets/animal-guard-yard-poster.webp",
        hideHero: true,
      },
    },
    {
      id: "animal-quiz",
      title: { en: "Animal Quiz", "zh-Hant": "動物小博士" },
      status: "playable",
      statusText: { en: "Playable", "zh-Hant": "可遊玩" },
      type: { en: "Family Quiz", "zh-Hant": "親子問答" },
      categories: ["Animal Games", "Education", "Family"],
      skills: ["Animal Knowledge", "Memory", "Reading"],
      ages: ["3", "5", "family"],
      ageLabel: { en: "Family", "zh-Hant": "親子" },
      href: "games/animal-quiz/",
      description: {
        en: "Clear animal stages with short, friendly quiz questions.",
        "zh-Hant": "用簡短友善的問答完成動物知識關卡。",
      },
      meta: {
        en: ["Animal Games", "5 Stages", "Quiz"],
        "zh-Hant": ["動物遊戲", "5 關", "問答"],
      },
      art: {
        kind: "image",
        background: "assets/quiz-cover.png",
        hero: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='1' height='1'></svg>",
      },
    },
    {
      id: "zoo-helper-day",
      title: { en: "Zoo Helper Day", "zh-Hant": "動物園幫忙日" },
      status: "playable",
      statusText: { en: "Playable", "zh-Hant": "可遊玩" },
      type: { en: "Animal Care", "zh-Hant": "動物照顧" },
      categories: ["Animal Games", "Education", "Family"],
      skills: ["Animal Knowledge", "Focus", "Hand-Eye Coordination"],
      ages: ["3", "5", "family"],
      ageLabel: { en: "3+", "zh-Hant": "3+" },
      href: "games/zoo-helper-day/",
      description: {
        en: "Help zoo animals with simple care choices made for young players.",
        "zh-Hant": "用簡單選擇幫動物園的小動物完成照顧任務。",
      },
      meta: {
        en: ["Zoo Animals", "Care Choices", "Kids"],
        "zh-Hant": ["動物園", "照顧選擇", "兒童"],
      },
      art: {
        kind: "image",
        background: "assets/zoo-helper-day-cover.webp",
        hero: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='1' height='1'></svg>",
      },
    },
    {
      id: "shape-train",
      title: { en: "Animal Shape Train", "zh-Hant": "動物形狀小火車" },
      status: "playable",
      statusText: { en: "Playable", "zh-Hant": "可遊玩" },
      type: { en: "Shape Puzzle", "zh-Hant": "形狀益智" },
      categories: ["Animal Games", "Education", "Puzzle", "Family"],
      skills: ["Color Recognition", "Logic", "Hand-Eye Coordination"],
      ages: ["3", "family"],
      ageLabel: { en: "3+", "zh-Hant": "3+" },
      href: "games/shape-train/",
      description: {
        en: "Match animal cargo by shape and color in a gentle train puzzle.",
        "zh-Hant": "依照形狀和顏色，把動物貨物放到小火車上。",
      },
      meta: {
        en: ["Shapes", "Colors", "Train"],
        "zh-Hant": ["形狀", "顏色", "小火車"],
      },
      art: {
        kind: "image",
        background: "assets/shape-train-cover.webp",
        hero: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='1' height='1'></svg>",
      },
    },
    {
      id: "tiny-weather-rescue",
      title: { en: "Animal Helper Quest", "zh-Hant": "動物幫幫隊" },
      status: "playable",
      statusText: { en: "Playable", "zh-Hant": "可遊玩" },
      type: { en: "Problem Puzzle", "zh-Hant": "情境益智" },
      categories: ["Animal Games", "Puzzle", "Family"],
      skills: ["Problem Solving", "Animal Knowledge", "Focus"],
      ages: ["5", "family"],
      ageLabel: { en: "5+", "zh-Hant": "5+" },
      href: "games/tiny-weather-rescue/",
      description: {
        en: "Pick helpful tools for animal scenes and solve simple everyday problems.",
        "zh-Hant": "依照動物遇到的情境，選出合適道具幫忙解決問題。",
      },
      meta: {
        en: ["Animal Help", "Scene Puzzle", "Kids"],
        "zh-Hant": ["動物幫忙", "情境益智", "兒童"],
      },
      art: {
        kind: "image",
        background: "assets/tiny-weather-rescue-cover.webp",
        hero: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='1' height='1'></svg>",
      },
    },
  ],
};
